/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simakademik;

import java.sql.*;
import javax.swing.*;
import javax.xml.crypto.Data;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ALFARIS
 */
public class DataMatakuliah extends javax.swing.JFrame {
    
 Connection con = null;
	ResultSet rs = null;
	PreparedStatement pst = null;
	Statement statBrg;
	Boolean ada = false;
        
        private void koneksi() {
	try{
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost/sim_akademik"; 
            String user="root"; 
            String pass=""; 
            con = DriverManager.getConnection(url,user,pass);
            statBrg = con.createStatement(rs.TYPE_SCROLL_SENSITIVE,rs.CONCUR_UPDATABLE);
            rs = statBrg.executeQuery("select * from matakuliah");
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                System.exit(0);
            }
    }
        private void display(){
        try{
            String sql="select * from matakuliah";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
 }
    private void Clear() {
        jTextField1.setText("");
        jComboBox1.setSelectedIndex(0); 
        jTextField3.setText("");
    }
    public DataMatakuliah() {
        initComponents();
        koneksi();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnMahasiswa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMatkul = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPerkuliahan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnDosen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMahasiswa.setBackground(new java.awt.Color(85, 65, 118));
        btnMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMahasiswaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Mahasiswa");

        javax.swing.GroupLayout btnMahasiswaLayout = new javax.swing.GroupLayout(btnMahasiswa);
        btnMahasiswa.setLayout(btnMahasiswaLayout);
        btnMahasiswaLayout.setHorizontalGroup(
            btnMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMahasiswaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnMahasiswaLayout.setVerticalGroup(
            btnMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMahasiswaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(btnMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 40));

        btnMatkul.setBackground(new java.awt.Color(64, 43, 100));
        btnMatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMatkulMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Mata Kuliah");

        javax.swing.GroupLayout btnMatkulLayout = new javax.swing.GroupLayout(btnMatkul);
        btnMatkul.setLayout(btnMatkulLayout);
        btnMatkulLayout.setHorizontalGroup(
            btnMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMatkulLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnMatkulLayout.setVerticalGroup(
            btnMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMatkulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(btnMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, 40));

        btnPerkuliahan.setBackground(new java.awt.Color(64, 43, 100));
        btnPerkuliahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerkuliahanMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Perkuliahan");

        javax.swing.GroupLayout btnPerkuliahanLayout = new javax.swing.GroupLayout(btnPerkuliahan);
        btnPerkuliahan.setLayout(btnPerkuliahanLayout);
        btnPerkuliahanLayout.setHorizontalGroup(
            btnPerkuliahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPerkuliahanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnPerkuliahanLayout.setVerticalGroup(
            btnPerkuliahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPerkuliahanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(btnPerkuliahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, 40));

        btnDosen.setBackground(new java.awt.Color(64, 43, 100));
        btnDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDosenMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Dosen");

        javax.swing.GroupLayout btnDosenLayout = new javax.swing.GroupLayout(btnDosen);
        btnDosen.setLayout(btnDosenLayout);
        btnDosenLayout.setHorizontalGroup(
            btnDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDosenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnDosenLayout.setVerticalGroup(
            btnDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDosenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(btnDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SIM Perkuliahan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logoPoltek.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("_________________________________________________");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 20));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 555));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setAutoscrolls(true);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Daftar Mata Kuliah ________________________________");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Home/DataMataKuliah/");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(16, 16, 16))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 34, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode MK", "Nama MK", "SKS"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 317, 665, 218));

        btnTambah.setBackground(new java.awt.Color(0, 102, 255));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        bg.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 282, 82, -1));

        btnEdit.setBackground(new java.awt.Color(255, 153, 51));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        bg.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 282, 78, -1));

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        bg.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 282, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Kode MK");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 178, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Nama MK");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 211, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("SKS");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 245, 81, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        bg.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 175, 90, -1));
        bg.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 242, 37, -1));

        btnLogout.setBackground(new java.awt.Color(204, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        bg.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 282, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel14.setText("By: Dzakwan alfaris | 234311019");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 8, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemrograman Berbasis Web 1", "Praktik Pemrograman Berbasis Web", "MMPPL", "Sistem Operasi", "Teknologi Informasi", "Pemrograman Berbasis Objek", "Praktik Pemrograman Berbasis Objek", "Pendidikan Agama", "APPL", "Struktur Data" }));
        bg.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 209, 225, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String kodeMK = jTextField1.getText().trim();
        String namaMK = jComboBox1.getSelectedItem().toString();
        String sks = jTextField3.getText().trim();
        try {
            koneksi();
            String query = "UPDATE matakuliah SET Nama_Mk = ?, Sks = ? WHERE Kode_Mk = ?";
            PreparedStatement preparedStmt = con.prepareStatement(query);
            preparedStmt.setString(1, namaMK);
            preparedStmt.setInt(2, Integer.parseInt(sks));
            preparedStmt.setString(3, kodeMK);

            preparedStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
            display(); 
            Clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error saat memperbarui data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
        koneksi();
        int row = jTable1.getSelectedRow();
        String tableClick = (jTable1.getModel().getValueAt(row, 0).toString());
        Statement stm = con.createStatement();
        ResultSet rs = stm.executeQuery("SELECT * FROM matakuliah WHERE Kode_Mk ='" + tableClick + "'");
        if (rs.next()) {
            String kodeMK = rs.getString("Kode_Mk");
            jTextField1.setText(kodeMK);
            String namaMK = rs.getString("Nama_Mk");
            jComboBox1.setSelectedItem(namaMK);
            String sks = rs.getString("Sks");
            jTextField3.setText(sks);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    } 
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDosenMouseClicked
        DataDosen dataDosenFrame = new DataDosen(); 
        dataDosenFrame.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnDosenMouseClicked

    private void btnMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMahasiswaMouseClicked
        DataMahasiswa dataMahasiswa = new DataMahasiswa();
        dataMahasiswa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMahasiswaMouseClicked

    private void btnMatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMatkulMouseClicked
        DataMatakuliah dataMatakuliah = new DataMatakuliah();
        dataMatakuliah.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMatkulMouseClicked

    private void btnPerkuliahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerkuliahanMouseClicked
        DataPerkuliahan dataPerkuliahan = new DataPerkuliahan();
        dataPerkuliahan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerkuliahanMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String kodeMK = jTextField1.getText().trim();
        String namaMK = jComboBox1.getSelectedItem().toString();
        String sks = jTextField3.getText().trim();
        try {
            String query = "INSERT INTO matakuliah (Kode_Mk, Nama_Mk, Sks) VALUES (?, ?, ?)";
            PreparedStatement preparedStmt = con.prepareStatement(query);
            preparedStmt.setString(1, kodeMK);
            preparedStmt.setString(2, namaMK);
            preparedStmt.setInt(3, Integer.parseInt(sks));

            preparedStmt.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
            display(); 
            Clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error saat menambah data: " + e.getMessage());
        }        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String kodeMK = jTextField1.getText().trim();
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            koneksi();
            String query = "DELETE FROM matakuliah WHERE Kode_Mk = ?";
            PreparedStatement preparedStmt = con.prepareStatement(query);
            preparedStmt.setString(1, kodeMK);

            preparedStmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            display(); 
            Clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error saat menghapus data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMatakuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnDosen;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel btnMahasiswa;
    private javax.swing.JPanel btnMatkul;
    private javax.swing.JPanel btnPerkuliahan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
